package benbenxiong.java.demo.model;

public class Publish {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column publish.id
     *
     * @mbg.generated Wed Aug 14 00:13:50 CST 2019
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column publish.uid
     *
     * @mbg.generated Wed Aug 14 00:13:50 CST 2019
     */
    private Integer uid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column publish.title
     *
     * @mbg.generated Wed Aug 14 00:13:50 CST 2019
     */
    private String title;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column publish.lab
     *
     * @mbg.generated Wed Aug 14 00:13:50 CST 2019
     */
    private String lab;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column publish.scan_num
     *
     * @mbg.generated Wed Aug 14 00:13:50 CST 2019
     */
    private Integer scanNum;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column publish.like_num
     *
     * @mbg.generated Wed Aug 14 00:13:50 CST 2019
     */
    private Integer likeNum;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column publish.attention_num
     *
     * @mbg.generated Wed Aug 14 00:13:50 CST 2019
     */
    private Integer attentionNum;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column publish.reply_num
     *
     * @mbg.generated Wed Aug 14 00:13:50 CST 2019
     */
    private Integer replyNum;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column publish.created_at
     *
     * @mbg.generated Wed Aug 14 00:13:50 CST 2019
     */
    private Long createdAt;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column publish.updated_at
     *
     * @mbg.generated Wed Aug 14 00:13:50 CST 2019
     */
    private Long updatedAt;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column publish.desc
     *
     * @mbg.generated Wed Aug 14 00:13:50 CST 2019
     */
    private String desc;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column publish.id
     *
     * @return the value of publish.id
     *
     * @mbg.generated Wed Aug 14 00:13:50 CST 2019
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column publish.id
     *
     * @param id the value for publish.id
     *
     * @mbg.generated Wed Aug 14 00:13:50 CST 2019
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column publish.uid
     *
     * @return the value of publish.uid
     *
     * @mbg.generated Wed Aug 14 00:13:50 CST 2019
     */
    public Integer getUid() {
        return uid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column publish.uid
     *
     * @param uid the value for publish.uid
     *
     * @mbg.generated Wed Aug 14 00:13:50 CST 2019
     */
    public void setUid(Integer uid) {
        this.uid = uid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column publish.title
     *
     * @return the value of publish.title
     *
     * @mbg.generated Wed Aug 14 00:13:50 CST 2019
     */
    public String getTitle() {
        return title;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column publish.title
     *
     * @param title the value for publish.title
     *
     * @mbg.generated Wed Aug 14 00:13:50 CST 2019
     */
    public void setTitle(String title) {
        this.title = title == null ? null : title.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column publish.lab
     *
     * @return the value of publish.lab
     *
     * @mbg.generated Wed Aug 14 00:13:50 CST 2019
     */
    public String getLab() {
        return lab;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column publish.lab
     *
     * @param lab the value for publish.lab
     *
     * @mbg.generated Wed Aug 14 00:13:50 CST 2019
     */
    public void setLab(String lab) {
        this.lab = lab == null ? null : lab.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column publish.scan_num
     *
     * @return the value of publish.scan_num
     *
     * @mbg.generated Wed Aug 14 00:13:50 CST 2019
     */
    public Integer getScanNum() {
        return scanNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column publish.scan_num
     *
     * @param scanNum the value for publish.scan_num
     *
     * @mbg.generated Wed Aug 14 00:13:50 CST 2019
     */
    public void setScanNum(Integer scanNum) {
        this.scanNum = scanNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column publish.like_num
     *
     * @return the value of publish.like_num
     *
     * @mbg.generated Wed Aug 14 00:13:50 CST 2019
     */
    public Integer getLikeNum() {
        return likeNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column publish.like_num
     *
     * @param likeNum the value for publish.like_num
     *
     * @mbg.generated Wed Aug 14 00:13:50 CST 2019
     */
    public void setLikeNum(Integer likeNum) {
        this.likeNum = likeNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column publish.attention_num
     *
     * @return the value of publish.attention_num
     *
     * @mbg.generated Wed Aug 14 00:13:50 CST 2019
     */
    public Integer getAttentionNum() {
        return attentionNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column publish.attention_num
     *
     * @param attentionNum the value for publish.attention_num
     *
     * @mbg.generated Wed Aug 14 00:13:50 CST 2019
     */
    public void setAttentionNum(Integer attentionNum) {
        this.attentionNum = attentionNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column publish.reply_num
     *
     * @return the value of publish.reply_num
     *
     * @mbg.generated Wed Aug 14 00:13:50 CST 2019
     */
    public Integer getReplyNum() {
        return replyNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column publish.reply_num
     *
     * @param replyNum the value for publish.reply_num
     *
     * @mbg.generated Wed Aug 14 00:13:50 CST 2019
     */
    public void setReplyNum(Integer replyNum) {
        this.replyNum = replyNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column publish.created_at
     *
     * @return the value of publish.created_at
     *
     * @mbg.generated Wed Aug 14 00:13:50 CST 2019
     */
    public Long getCreatedAt() {
        return createdAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column publish.created_at
     *
     * @param createdAt the value for publish.created_at
     *
     * @mbg.generated Wed Aug 14 00:13:50 CST 2019
     */
    public void setCreatedAt(Long createdAt) {
        this.createdAt = createdAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column publish.updated_at
     *
     * @return the value of publish.updated_at
     *
     * @mbg.generated Wed Aug 14 00:13:50 CST 2019
     */
    public Long getUpdatedAt() {
        return updatedAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column publish.updated_at
     *
     * @param updatedAt the value for publish.updated_at
     *
     * @mbg.generated Wed Aug 14 00:13:50 CST 2019
     */
    public void setUpdatedAt(Long updatedAt) {
        this.updatedAt = updatedAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column publish.desc
     *
     * @return the value of publish.desc
     *
     * @mbg.generated Wed Aug 14 00:13:50 CST 2019
     */
    public String getDesc() {
        return desc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column publish.desc
     *
     * @param desc the value for publish.desc
     *
     * @mbg.generated Wed Aug 14 00:13:50 CST 2019
     */
    public void setDesc(String desc) {
        this.desc = desc == null ? null : desc.trim();
    }
}