package benbenxiong.java.demo.mapper;

import benbenxiong.java.demo.model.Publish;
import benbenxiong.java.demo.model.PublishExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;

public interface PublishMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table publish
     *
     * @mbg.generated Wed Aug 14 00:13:50 CST 2019
     */
    long countByExample(PublishExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table publish
     *
     * @mbg.generated Wed Aug 14 00:13:50 CST 2019
     */
    int deleteByExample(PublishExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table publish
     *
     * @mbg.generated Wed Aug 14 00:13:50 CST 2019
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table publish
     *
     * @mbg.generated Wed Aug 14 00:13:50 CST 2019
     */
    int insert(Publish record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table publish
     *
     * @mbg.generated Wed Aug 14 00:13:50 CST 2019
     */
    int insertSelective(Publish record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table publish
     *
     * @mbg.generated Wed Aug 14 00:13:50 CST 2019
     */
    List<Publish> selectByExampleWithBLOBsWithRowbounds(PublishExample example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table publish
     *
     * @mbg.generated Wed Aug 14 00:13:50 CST 2019
     */
    List<Publish> selectByExampleWithBLOBs(PublishExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table publish
     *
     * @mbg.generated Wed Aug 14 00:13:50 CST 2019
     */
    List<Publish> selectByExampleWithRowbounds(PublishExample example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table publish
     *
     * @mbg.generated Wed Aug 14 00:13:50 CST 2019
     */
    List<Publish> selectByExample(PublishExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table publish
     *
     * @mbg.generated Wed Aug 14 00:13:50 CST 2019
     */
    Publish selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table publish
     *
     * @mbg.generated Wed Aug 14 00:13:50 CST 2019
     */
    int updateByExampleSelective(@Param("record") Publish record, @Param("example") PublishExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table publish
     *
     * @mbg.generated Wed Aug 14 00:13:50 CST 2019
     */
    int updateByExampleWithBLOBs(@Param("record") Publish record, @Param("example") PublishExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table publish
     *
     * @mbg.generated Wed Aug 14 00:13:50 CST 2019
     */
    int updateByExample(@Param("record") Publish record, @Param("example") PublishExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table publish
     *
     * @mbg.generated Wed Aug 14 00:13:50 CST 2019
     */
    int updateByPrimaryKeySelective(Publish record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table publish
     *
     * @mbg.generated Wed Aug 14 00:13:50 CST 2019
     */
    int updateByPrimaryKeyWithBLOBs(Publish record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table publish
     *
     * @mbg.generated Wed Aug 14 00:13:50 CST 2019
     */
    int updateByPrimaryKey(Publish record);
}